# All the groups here
---

# Ungrouped Hosts need names and go into the default group
UngroupedHosts:
  - Name: home_server
    Description: This is the main server
    Host: 192.168.1.106:22
    User: angus

  - Name: hetzner_testserver
    Description: This is the main server
    Host: 135.181.248.151:22
    User: root

SomeGroup:
  - Name: home_server1
    Description: This is the main server
    Host: 192.168.1.106:22
    User: angus
    

# All the group and host vars 
---
home_server:
  some_var: some value
  test_message: "The config also works"
  test_obj.lol: "this is a test"
    
  
SomeGroup:
  some_var: some other value
  


